# Generated by Django 4.0.3 on 2022-03-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('clima', models.CharField(max_length=20)),
                ('diametro', models.IntegerField()),
                ('populacao', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Planeta',
                'verbose_name_plural': 'Planetas',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_lancamento', models.DateTimeField(null=True)),
                ('planetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.planeta')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
    ]
