# Generated by Django 4.0.3 on 2022-03-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filme',
            options={'ordering': ['-pk'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='planeta',
            options={'ordering': ['-pk'], 'verbose_name': 'Planeta', 'verbose_name_plural': 'Planetas'},
        ),
    ]
